version: '3'
services:
  db:
    image: postgres:9.4-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: MyCarsDb
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  app:
    #build: .
    image: bolotovmu/mycarsrestapi_app
    ports:
      - 8081:8080
    environment:
      POSTGRES_HOST: db
    restart: always
    links:
      - db
